#!/bin/sh

printf "\033[1;34mprogwi\033[1;32mshell \033[1;37m2.0\nmade for progwilinux!\033[0;37m\n"

while :
do
	printf "\033[1;33mprogwilinux\033[0;37m:>"
	read cmd arg
	
	if [ "$cmd" = "version" ]; then
		printf "\033[1;34mprogwi\033[1;32mshell \033[1;37m2.0\nmade for progwilinux!\033[0;37m\n"
	elif [ "$cmd" = "cf" ]; then
		cd $arg
	elif [ "$cmd" = "cd" ]; then
		pwd
	elif [ "$cmd" = "cnf" ]; then
		mkdir $arg
	elif [ "$cmd" = "print" ]; then
		echo $arg
	elif [ "$cmd" = "start" ]; then
		./$arg
	elif [ "$cmd" = "exit" ]; then
		exit
	elif [ "$cmd" = "dr" ]; then
		ls
	elif [ "$cmd" = "info" ]; then
		uname -a
	elif [ "$cmd" = "help" ]; then
		printf "\033[1;34mprogwi\033[1;32mshell \033[1;37m2.0\033[0;37m\nversion - Current progwishell version.\ncf - change folder.\ncd - current directory.\ncnf - create new folder.\nprint - print anything.\nstart - start a program.\nexit - exit progwishell.\nhelp - show commands list.\ndr - check directory.\n"
	fi
done
