#!/bin/sh

printf "\033[1;32mprogwishell \033[1;37m1.0\nby progwi0, made for progwilinux!\033[0;37m\n"

while :
do
	printf "\033[1;33mprogwilinux\033[0;37m:>"
	read cmd arg
	
	if [ "$cmd" = "version" ]; then
		printf "\033[1;34mprogwi\033[1;32mshell \033[1;37m1.0\nmade for progwilinux!\033[0;37m\n"
	else
		$cmd $arg
	fi
done
